### ISSUE TITLE
USB 3 operation

### ISSUE THREAD

**Issue by phodina** [will127534/Coral-USB3-M2-Module#2]
Hi @will127534 ,

so in order to get the USB 3 mode operation it's necessary to use PCIe to USB converter? There's no way to use the diff pairs directly and connect them straight to USB signals?

Is this the way how they do it on the consumer products such as the Coral USB module?

https://gitlab.com/phodina/coral-bay

**Comment by phodina** [comment]
Also what about the impedence matching? Guess the same for PCIe applies to USB signals, right?

![image](https://github.com/will127534/Coral-USB3-M2-Module/assets/2997905/f1ce6113-f234-48d7-bc86-3e07561910d3)

**Comment by will127534** [comment]
Have you checked the blog post about the project?

**Comment by phodina** [comment]
Have done that know. The link is broken. Fix in MR. https://github.com/will127534/Coral-USB3-M2-Module/pull/3

Yes, you explain that the PCIe diff pairs  can be used as USB 3 RX and TX pairs.

And as you use the M.2 module for Coral <-> USB 3 <-> VL805 <-> PCIe I can just use it directly.

Haven't checked the lengths in the PCB of the project but I guess the lines are tuned as required by the datasheet.

**Comment by will127534** [comment]
Thanks,

However I don't recommend you use Coral module for Framework Laptops, just pure CPU power should already be more then what Coral module can deliver, while iGPUs on shipping laptops can blow Coral module away on computing power and it is way easier to deploy ML models.

Don't waste your time on Coral module, it is an age old products without any updates.
